package com.androidkris.ide.terminal

import android.content.Context
import java.io.File

/**
 * Filesystem layout + shell environment for the on-device Linux prefix
 * (Fase 2.1), mirroring AndroidIDE/Termux: `$PREFIX = <files>/ide/usr`,
 * `$HOME = <files>/ide/home`. The bootstrap (bash + coreutils, compiled for
 * Android/bionic) is downloaded and extracted here by [BootstrapInstaller].
 *
 * Executing binaries from here requires `targetSdk = 28` (see app build.gradle).
 */
object Environment {

    lateinit var root: File
        private set
    lateinit var prefix: File
        private set
    lateinit var home: File
        private set
    lateinit var bin: File
        private set
    lateinit var lib: File
        private set
    lateinit var tmp: File
        private set
    lateinit var bash: File
        private set
    lateinit var aptConfig: File
        private set

    fun init(context: Context) {
        root = File(context.filesDir, "ide")
        prefix = File(root, "usr")
        home = File(root, "home")
        bin = File(prefix, "bin")
        lib = File(prefix, "lib")
        tmp = File(prefix, "tmp")
        bash = File(bin, "bash")
        aptConfig = File(prefix, "etc/apt/apt.conf.d/00androidkris-prefix.conf")
    }

    /** True once the bootstrap is extracted and bash is executable. */
    val isInstalled: Boolean
        get() = this::bash.isInitialized && bash.canExecute()

    fun ensureRuntimeDirs() {
        home.mkdirs()
        tmp.mkdirs()
    }

    /** Environment for a login shell inside the prefix. */
    fun shellEnv(): Array<String> = arrayOf(
        "PREFIX=${prefix.absolutePath}",
        "HOME=${home.absolutePath}",
        "PATH=${bin.absolutePath}:/system/bin:/system/xbin",
        "LD_LIBRARY_PATH=${lib.absolutePath}",
        "TMPDIR=${tmp.absolutePath}",
        "TERM=xterm-256color",
        "LANG=en_US.UTF-8",
        // apt/dpkg compile in Dir::Etc pointing at Termux's own prefix, so they never look in
        // our etc/apt/apt.conf.d/ for the override generated by BootstrapInstaller. APT_CONFIG
        // is read before any compiled-in default, bypassing that chicken-and-egg problem.
        "APT_CONFIG=${aptConfig.absolutePath}",
    )

    // Termux's own official bootstrap, aarch64 (bash + coreutils + apt/dpkg/curl/nano/...).
    // AndroidIDE (previously used here) was discontinued in Dec 2024 (org archived); Termux's
    // own bootstrap is still built weekly and is a superset (adds apt/dpkg, needed for Fase
    // 2.1b). A handful of apt/dpkg paths are hardcoded to Termux's own prefix at compile time
    // — see BootstrapInstaller's symlink retargeting + generated apt.conf override.
    const val BOOTSTRAP_URL =
        "https://github.com/termux/termux-packages/releases/download/bootstrap-2026.07.05-r1+apt.android-7/bootstrap-aarch64.zip"
    const val BOOTSTRAP_SHA256 =
        "e976289d117a94f6acc969096d8e3c01d54a53024416cd0279d84cac11458ab8"
}
